// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: core.sql

package dbgen

import (
	"context"
	"time"
)

const ensureUser = `-- name: EnsureUser :one
INSERT INTO sonata.users (id, updated_at)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE
SET updated_at = GREATEST(sonata.users.updated_at, EXCLUDED.updated_at)
RETURNING id, created_at, updated_at
`

type EnsureUserParams struct {
	OwnerID   string    `json:"owner_id"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) EnsureUser(ctx context.Context, arg EnsureUserParams) (User, error) {
	row := q.db.QueryRow(ctx, ensureUser, arg.OwnerID, arg.UpdatedAt)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const insertMessage = `-- name: InsertMessage :one
INSERT INTO sonata.messages (
    owner_id,
    conversation_id,
    id,
    role,
    content,
    created_at
)
VALUES ($1, $2, $3, $4, $5::jsonb, $6)
RETURNING owner_id, conversation_id, id, role, content, created_at
`

type InsertMessageParams struct {
	OwnerID        string    `json:"owner_id"`
	ConversationID string    `json:"conversation_id"`
	MessageID      string    `json:"message_id"`
	Role           string    `json:"role"`
	Content        []byte    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.OwnerID,
		arg.ConversationID,
		arg.MessageID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.OwnerID,
		&i.ConversationID,
		&i.ID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const listConversationMessages = `-- name: ListConversationMessages :many
SELECT owner_id, conversation_id, id, role, content, created_at
FROM sonata.messages
WHERE owner_id = $1
  AND conversation_id = $2
ORDER BY created_at, id
LIMIT $3
`

type ListConversationMessagesParams struct {
	OwnerID        string `json:"owner_id"`
	ConversationID string `json:"conversation_id"`
	LimitCount     int32  `json:"limit_count"`
}

func (q *Queries) ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listConversationMessages, arg.OwnerID, arg.ConversationID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.OwnerID,
			&i.ConversationID,
			&i.ID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConversation = `-- name: UpsertConversation :one
INSERT INTO sonata.conversations (
    owner_id,
    id,
    title,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (owner_id, id) DO UPDATE
SET title = EXCLUDED.title,
    updated_at = GREATEST(sonata.conversations.updated_at, EXCLUDED.updated_at)
RETURNING owner_id, id, title, created_at, updated_at
`

type UpsertConversationParams struct {
	OwnerID        string    `json:"owner_id"`
	ConversationID string    `json:"conversation_id"`
	Title          string    `json:"title"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

func (q *Queries) UpsertConversation(ctx context.Context, arg UpsertConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, upsertConversation,
		arg.OwnerID,
		arg.ConversationID,
		arg.Title,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Conversation
	err := row.Scan(&i.OwnerID, &i.ID, &i.Title, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}
