// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: instructions.sql

package dbgen

import (
	"context"
	"time"
)

const getInstructionVersion = `-- name: GetInstructionVersion :one
SELECT instruction_id, version, content_hash, metadata, created_at
FROM sonata.instruction_versions
WHERE instruction_id = $1
  AND version = $2
`

type GetInstructionVersionParams struct {
	InstructionID string `json:"instruction_id"`
	Version       int32  `json:"version"`
}

func (q *Queries) GetInstructionVersion(ctx context.Context, arg GetInstructionVersionParams) (InstructionVersion, error) {
	row := q.db.QueryRow(ctx, getInstructionVersion, arg.InstructionID, arg.Version)
	var i InstructionVersion
	err := row.Scan(
		&i.InstructionID,
		&i.Version,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const upsertInstructionVersion = `-- name: UpsertInstructionVersion :one
INSERT INTO sonata.instruction_versions (
    instruction_id,
    version,
    content_hash,
    metadata,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4::jsonb,
    $5
)
ON CONFLICT (instruction_id, version) DO UPDATE
SET content_hash = EXCLUDED.content_hash,
    metadata = EXCLUDED.metadata,
    created_at = EXCLUDED.created_at
RETURNING instruction_id, version, content_hash, metadata, created_at
`

type UpsertInstructionVersionParams struct {
	InstructionID string    `json:"instruction_id"`
	Version       int32     `json:"version"`
	ContentHash   string    `json:"content_hash"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) UpsertInstructionVersion(ctx context.Context, arg UpsertInstructionVersionParams) (InstructionVersion, error) {
	row := q.db.QueryRow(ctx, upsertInstructionVersion,
		arg.InstructionID,
		arg.Version,
		arg.ContentHash,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i InstructionVersion
	err := row.Scan(
		&i.InstructionID,
		&i.Version,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
