// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: manifests.sql

package dbgen

import (
	"context"
	"time"
)

const deleteUserManifest = `-- name: DeleteUserManifest :one
UPDATE sonata.user_manifests
SET status = 'deleted',
    content = '',
    updated_at = $1
WHERE owner_id = $2
  AND scope = $3
  AND scope_id = $4
RETURNING owner_id, scope, scope_id, manifest_id, version, status, content, content_hash, created_at, updated_at
`

type DeleteUserManifestParams struct {
	UpdatedAt time.Time `json:"updated_at"`
	OwnerID   string    `json:"owner_id"`
	Scope     string    `json:"scope"`
	ScopeID   string    `json:"scope_id"`
}

func (q *Queries) DeleteUserManifest(ctx context.Context, arg DeleteUserManifestParams) (UserManifest, error) {
	row := q.db.QueryRow(ctx, deleteUserManifest, arg.UpdatedAt, arg.OwnerID, arg.Scope, arg.ScopeID)
	var i UserManifest
	err := scanUserManifest(row.Scan, &i)
	return i, err
}

const getUserManifest = `-- name: GetUserManifest :one
SELECT owner_id, scope, scope_id, manifest_id, version, status, content, content_hash, created_at, updated_at
FROM sonata.user_manifests
WHERE owner_id = $1
  AND scope = $2
  AND scope_id = $3
`

type GetUserManifestParams struct {
	OwnerID string `json:"owner_id"`
	Scope   string `json:"scope"`
	ScopeID string `json:"scope_id"`
}

func (q *Queries) GetUserManifest(ctx context.Context, arg GetUserManifestParams) (UserManifest, error) {
	row := q.db.QueryRow(ctx, getUserManifest, arg.OwnerID, arg.Scope, arg.ScopeID)
	var i UserManifest
	err := scanUserManifest(row.Scan, &i)
	return i, err
}

const insertManifestVersion = `-- name: InsertManifestVersion :one
INSERT INTO sonata.manifest_versions (
    manifest_id,
    version,
    owner_id,
    source,
    content_hash,
    metadata,
    created_at
)
VALUES ($1, $2, $3, $4, $5, $6::jsonb, $7)
RETURNING manifest_id, version, owner_id, source, content_hash, metadata, created_at
`

type InsertManifestVersionParams struct {
	ManifestID  string    `json:"manifest_id"`
	Version     int32     `json:"version"`
	OwnerID     *string   `json:"owner_id"`
	Source      string    `json:"source"`
	ContentHash string    `json:"content_hash"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) InsertManifestVersion(ctx context.Context, arg InsertManifestVersionParams) (ManifestVersion, error) {
	row := q.db.QueryRow(ctx, insertManifestVersion,
		arg.ManifestID,
		arg.Version,
		arg.OwnerID,
		arg.Source,
		arg.ContentHash,
		arg.Metadata,
		arg.CreatedAt,
	)
	var i ManifestVersion
	err := row.Scan(
		&i.ManifestID,
		&i.Version,
		&i.OwnerID,
		&i.Source,
		&i.ContentHash,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserManifest = `-- name: UpsertUserManifest :one
INSERT INTO sonata.user_manifests (
    owner_id,
    scope,
    scope_id,
    manifest_id,
    version,
    status,
    content,
    content_hash,
    created_at,
    updated_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (owner_id, scope, scope_id) DO UPDATE
SET manifest_id = EXCLUDED.manifest_id,
    version = EXCLUDED.version,
    status = EXCLUDED.status,
    content = EXCLUDED.content,
    content_hash = EXCLUDED.content_hash,
    updated_at = EXCLUDED.updated_at
RETURNING owner_id, scope, scope_id, manifest_id, version, status, content, content_hash, created_at, updated_at
`

type UpsertUserManifestParams struct {
	OwnerID     string    `json:"owner_id"`
	Scope       string    `json:"scope"`
	ScopeID     string    `json:"scope_id"`
	ManifestID  string    `json:"manifest_id"`
	Version     int32     `json:"version"`
	Status      string    `json:"status"`
	Content     string    `json:"content"`
	ContentHash string    `json:"content_hash"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpsertUserManifest(ctx context.Context, arg UpsertUserManifestParams) (UserManifest, error) {
	row := q.db.QueryRow(ctx, upsertUserManifest,
		arg.OwnerID,
		arg.Scope,
		arg.ScopeID,
		arg.ManifestID,
		arg.Version,
		arg.Status,
		arg.Content,
		arg.ContentHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserManifest
	err := scanUserManifest(row.Scan, &i)
	return i, err
}

func scanUserManifest(scan scanFunction, item *UserManifest) error {
	return scan(
		&item.OwnerID,
		&item.Scope,
		&item.ScopeID,
		&item.ManifestID,
		&item.Version,
		&item.Status,
		&item.Content,
		&item.ContentHash,
		&item.CreatedAt,
		&item.UpdatedAt,
	)
}
