// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type CognitiveRun struct {
	ID               pgtype.UUID `json:"id"`
	OwnerID          string      `json:"owner_id"`
	ConversationID   string      `json:"conversation_id"`
	RequestMessageID string      `json:"request_message_id"`
	Route            string      `json:"route"`
	Status           string      `json:"status"`
	StartedAt        time.Time   `json:"started_at"`
	CompletedAt      *time.Time  `json:"completed_at"`
	Metadata         []byte      `json:"metadata"`
}

type Conversation struct {
	OwnerID   string    `json:"owner_id"`
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type InstructionVersion struct {
	InstructionID string    `json:"instruction_id"`
	Version       int32     `json:"version"`
	ContentHash   string    `json:"content_hash"`
	Metadata      []byte    `json:"metadata"`
	CreatedAt     time.Time `json:"created_at"`
}

type ManifestVersion struct {
	ManifestID  string    `json:"manifest_id"`
	Version     int32     `json:"version"`
	OwnerID     *string   `json:"owner_id"`
	Source      string    `json:"source"`
	ContentHash string    `json:"content_hash"`
	Metadata    []byte    `json:"metadata"`
	CreatedAt   time.Time `json:"created_at"`
}

type Message struct {
	OwnerID        string    `json:"owner_id"`
	ConversationID string    `json:"conversation_id"`
	ID             string    `json:"id"`
	Role           string    `json:"role"`
	Content        []byte    `json:"content"`
	CreatedAt      time.Time `json:"created_at"`
}

type OutboxEvent struct {
	ID            pgtype.UUID `json:"id"`
	OwnerID       *string     `json:"owner_id"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   string      `json:"aggregate_id"`
	EventType     string      `json:"event_type"`
	Payload       []byte      `json:"payload"`
	Status        string      `json:"status"`
	Attempts      int32       `json:"attempts"`
	AvailableAt   time.Time   `json:"available_at"`
	LockedAt      *time.Time  `json:"locked_at"`
	ProcessedAt   *time.Time  `json:"processed_at"`
	LastErrorCode string      `json:"last_error_code"`
	CreatedAt     time.Time   `json:"created_at"`
}

type ProviderUsage struct {
	ID             pgtype.UUID `json:"id"`
	OwnerID        string      `json:"owner_id"`
	CognitiveRunID pgtype.UUID `json:"cognitive_run_id"`
	RoleRunID      pgtype.UUID `json:"role_run_id"`
	Provider       string      `json:"provider"`
	ModelID        string      `json:"model_id"`
	InputTokens    int64       `json:"input_tokens"`
	OutputTokens   int64       `json:"output_tokens"`
	CachedTokens   int64       `json:"cached_tokens"`
	CreatedAt      time.Time   `json:"created_at"`
}

type RoleRun struct {
	ID                 pgtype.UUID `json:"id"`
	OwnerID            string      `json:"owner_id"`
	CognitiveRunID     pgtype.UUID `json:"cognitive_run_id"`
	Phase              string      `json:"phase"`
	Perspective        string      `json:"perspective"`
	Status             string      `json:"status"`
	ModelID            string      `json:"model_id"`
	InstructionID      string      `json:"instruction_id"`
	InstructionVersion int32       `json:"instruction_version"`
	InstructionHash    string      `json:"instruction_hash"`
	ManifestID         string      `json:"manifest_id"`
	ManifestVersion    int32       `json:"manifest_version"`
	ManifestHash       string      `json:"manifest_hash"`
	LatencyMs          int64       `json:"latency_ms"`
	Usage              []byte      `json:"usage"`
	ErrorCode          string      `json:"error_code"`
	CreatedAt          time.Time   `json:"created_at"`
	ManifestSource     string      `json:"manifest_source"`
}

type ToolCall struct {
	ID              pgtype.UUID `json:"id"`
	OwnerID         string      `json:"owner_id"`
	CognitiveRunID  pgtype.UUID `json:"cognitive_run_id"`
	RoleRunID       pgtype.UUID `json:"role_run_id"`
	ToolName        string      `json:"tool_name"`
	Status          string      `json:"status"`
	RequestMetadata []byte      `json:"request_metadata"`
	ResultMetadata  []byte      `json:"result_metadata"`
	CreatedAt       time.Time   `json:"created_at"`
	CompletedAt     *time.Time  `json:"completed_at"`
}

type User struct {
	ID        string    `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserManifest struct {
	OwnerID     string    `json:"owner_id"`
	Scope       string    `json:"scope"`
	ScopeID     string    `json:"scope_id"`
	ManifestID  string    `json:"manifest_id"`
	Version     int32     `json:"version"`
	Status      string    `json:"status"`
	Content     string    `json:"content"`
	ContentHash string    `json:"content_hash"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}
