// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: outbox.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeOutboxEvent = `-- name: CompleteOutboxEvent :one
UPDATE sonata.outbox_events
SET status = 'completed',
    processed_at = $1,
    attempts = attempts + 1
WHERE id = $2
  AND status = 'processing'
RETURNING id, status, attempts, processed_at
`

type CompleteOutboxEventParams struct {
	ProcessedAt *time.Time  `json:"processed_at"`
	ID          pgtype.UUID `json:"id"`
}

type CompleteOutboxEventRow struct {
	ID          pgtype.UUID `json:"id"`
	Status      string      `json:"status"`
	Attempts    int32       `json:"attempts"`
	ProcessedAt *time.Time  `json:"processed_at"`
}

func (q *Queries) CompleteOutboxEvent(ctx context.Context, arg CompleteOutboxEventParams) (CompleteOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, completeOutboxEvent, arg.ProcessedAt, arg.ID)
	var i CompleteOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Attempts,
		&i.ProcessedAt,
	)
	return i, err
}

const failOutboxEvent = `-- name: FailOutboxEvent :one
UPDATE sonata.outbox_events
SET status = $1,
    available_at = $2,
    last_error_code = $3,
    locked_at = NULL,
    attempts = attempts + 1
WHERE id = $4
  AND status = 'processing'
RETURNING id, status, attempts, available_at
`

type FailOutboxEventParams struct {
	Status          string      `json:"status"`
	NextAvailableAt time.Time   `json:"next_available_at"`
	LastErrorCode   string      `json:"last_error_code"`
	ID              pgtype.UUID `json:"id"`
}

type FailOutboxEventRow struct {
	ID          pgtype.UUID `json:"id"`
	Status      string      `json:"status"`
	Attempts    int32       `json:"attempts"`
	AvailableAt time.Time   `json:"available_at"`
}

func (q *Queries) FailOutboxEvent(ctx context.Context, arg FailOutboxEventParams) (FailOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, failOutboxEvent,
		arg.Status,
		arg.NextAvailableAt,
		arg.LastErrorCode,
		arg.ID,
	)
	var i FailOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO sonata.outbox_events (
    owner_id,
    aggregate_type,
    aggregate_id,
    event_type,
    payload,
    status,
    attempts,
    available_at,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5::jsonb,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, owner_id, aggregate_type, aggregate_id, event_type, payload, status, attempts, available_at, locked_at, processed_at, last_error_code, created_at
`

type InsertOutboxEventParams struct {
	OwnerID       *string   `json:"owner_id"`
	AggregateType string    `json:"aggregate_type"`
	AggregateID   string    `json:"aggregate_id"`
	EventType     string    `json:"event_type"`
	Payload       []byte    `json:"payload"`
	Status        string    `json:"status"`
	Attempts      int32     `json:"attempts"`
	AvailableAt   time.Time `json:"available_at"`
	CreatedAt     time.Time `json:"created_at"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.OwnerID,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Status,
		arg.Attempts,
		arg.AvailableAt,
		arg.CreatedAt,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.AggregateType,
		&i.AggregateID,
		&i.EventType,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.AvailableAt,
		&i.LockedAt,
		&i.ProcessedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const lockPendingOutboxEvents = `-- name: LockPendingOutboxEvents :many
UPDATE sonata.outbox_events AS outer_ev
SET status = 'processing',
    locked_at = $1
WHERE outer_ev.id IN (
    SELECT inner_ev.id
    FROM sonata.outbox_events AS inner_ev
    WHERE inner_ev.status IN ('pending', 'failed')
      AND inner_ev.available_at <= $2
    ORDER BY inner_ev.available_at, inner_ev.created_at, inner_ev.id
    LIMIT $3
    FOR UPDATE SKIP LOCKED
)
RETURNING id, owner_id, aggregate_type, aggregate_id, event_type, payload, status, attempts, available_at, locked_at, processed_at, last_error_code, created_at
`

type LockPendingOutboxEventsParams struct {
	LockedAt   *time.Time `json:"locked_at"`
	Now        time.Time  `json:"now"`
	LimitCount int32      `json:"limit_count"`
}

func (q *Queries) LockPendingOutboxEvents(ctx context.Context, arg LockPendingOutboxEventsParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, lockPendingOutboxEvents, arg.LockedAt, arg.Now, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.AvailableAt,
			&i.LockedAt,
			&i.ProcessedAt,
			&i.LastErrorCode,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
