// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CompleteCognitiveRun(ctx context.Context, arg CompleteCognitiveRunParams) (CognitiveRun, error)
	CompleteRoleRun(ctx context.Context, arg CompleteRoleRunParams) (RoleRun, error)
	CreateCognitiveRun(ctx context.Context, arg CreateCognitiveRunParams) (CognitiveRun, error)
	CreateRoleRun(ctx context.Context, arg CreateRoleRunParams) (RoleRun, error)
	DeleteUserManifest(ctx context.Context, arg DeleteUserManifestParams) (UserManifest, error)
	EnsureUser(ctx context.Context, arg EnsureUserParams) (User, error)
	GetCognitiveRun(ctx context.Context, arg GetCognitiveRunParams) (CognitiveRun, error)
	GetUserManifest(ctx context.Context, arg GetUserManifestParams) (UserManifest, error)
	GetUserManifestForUpdate(ctx context.Context, arg GetUserManifestForUpdateParams) (UserManifest, error)
	InsertManifestVersion(ctx context.Context, arg InsertManifestVersionParams) (ManifestVersion, error)
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]Message, error)
	ListRoleRuns(ctx context.Context, arg ListRoleRunsParams) ([]RoleRun, error)
	LockUserManifestScope(ctx context.Context, arg LockUserManifestScopeParams) error
	NewManifestID(ctx context.Context) (string, error)
	UpsertConversation(ctx context.Context, arg UpsertConversationParams) (Conversation, error)
	UpsertUserManifest(ctx context.Context, arg UpsertUserManifestParams) (UserManifest, error)
}

var _ Querier = (*Queries)(nil)
