// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"
)

type Querier interface {
	CompleteCognitiveRun(context.Context, CompleteCognitiveRunParams) (CognitiveRun, error)
	CompleteRoleRun(context.Context, CompleteRoleRunParams) (RoleRun, error)
	CreateCognitiveRun(context.Context, CreateCognitiveRunParams) (CognitiveRun, error)
	CreateRoleRun(context.Context, CreateRoleRunParams) (RoleRun, error)
	DeleteUserManifest(context.Context, DeleteUserManifestParams) (UserManifest, error)
	EnsureUser(context.Context, EnsureUserParams) (User, error)
	GetCognitiveRun(context.Context, GetCognitiveRunParams) (CognitiveRun, error)
	GetUserManifest(context.Context, GetUserManifestParams) (UserManifest, error)
	InsertManifestVersion(context.Context, InsertManifestVersionParams) (ManifestVersion, error)
	InsertMessage(context.Context, InsertMessageParams) (Message, error)
	ListConversationMessages(context.Context, ListConversationMessagesParams) ([]Message, error)
	ListRoleRuns(context.Context, ListRoleRunsParams) ([]RoleRun, error)
	UpsertConversation(context.Context, UpsertConversationParams) (Conversation, error)
	UpsertUserManifest(context.Context, UpsertUserManifestParams) (UserManifest, error)
}

var _ Querier = (*Queries)(nil)
