// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package dbgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeCognitiveRun = `-- name: CompleteCognitiveRun :one
UPDATE sonata.cognitive_runs AS run
SET status = $1,
    completed_at = $2,
    metadata = $3::jsonb
WHERE run.owner_id = $4
  AND run.id = $5
  AND run.status = 'RUNNING'
  AND NOT EXISTS (
      SELECT 1
      FROM sonata.role_runs AS role
      WHERE role.owner_id = run.owner_id
        AND role.cognitive_run_id = run.id
        AND role.status = 'RUNNING'
  )
  AND (
      $1 <> 'OK'
      OR NOT EXISTS (
          SELECT 1
          FROM sonata.role_runs AS role
          WHERE role.owner_id = run.owner_id
            AND role.cognitive_run_id = run.id
            AND role.status <> 'OK'
      )
  )
RETURNING run.id, run.owner_id, run.conversation_id, run.request_message_id, run.route, run.status, run.started_at, run.completed_at, run.metadata
`

type CompleteCognitiveRunParams struct {
	Status         string      `json:"status"`
	CompletedAt    *time.Time  `json:"completed_at"`
	Metadata       []byte      `json:"metadata"`
	OwnerID        string      `json:"owner_id"`
	CognitiveRunID pgtype.UUID `json:"cognitive_run_id"`
}

func (q *Queries) CompleteCognitiveRun(ctx context.Context, arg CompleteCognitiveRunParams) (CognitiveRun, error) {
	row := q.db.QueryRow(ctx, completeCognitiveRun,
		arg.Status,
		arg.CompletedAt,
		arg.Metadata,
		arg.OwnerID,
		arg.CognitiveRunID,
	)
	var i CognitiveRun
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.RequestMessageID,
		&i.Route,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const completeRoleRun = `-- name: CompleteRoleRun :one
UPDATE sonata.role_runs
SET status = $1,
    model_id = $2,
    latency_ms = $3,
    usage = $4::jsonb,
    error_code = $5
WHERE owner_id = $6
  AND cognitive_run_id = $7
  AND id = $8
  AND status = 'RUNNING'
  AND phase = $9
  AND perspective = $10
  AND instruction_id = $11
  AND instruction_version = $12
  AND instruction_hash = $13
  AND manifest_id = $14
  AND manifest_version = $15
  AND manifest_hash = $16
  AND manifest_source = $17
RETURNING id, owner_id, cognitive_run_id, phase, perspective, status, model_id, instruction_id, instruction_version, instruction_hash, manifest_id, manifest_version, manifest_hash, latency_ms, usage, error_code, created_at, manifest_source
`

type CompleteRoleRunParams struct {
	Status                     string      `json:"status"`
	ModelID                    string      `json:"model_id"`
	LatencyMs                  int64       `json:"latency_ms"`
	Usage                      []byte      `json:"usage"`
	ErrorCode                  string      `json:"error_code"`
	OwnerID                    string      `json:"owner_id"`
	CognitiveRunID             pgtype.UUID `json:"cognitive_run_id"`
	RoleRunID                  pgtype.UUID `json:"role_run_id"`
	ExpectedPhase              string      `json:"expected_phase"`
	ExpectedPerspective        string      `json:"expected_perspective"`
	ExpectedInstructionID      string      `json:"expected_instruction_id"`
	ExpectedInstructionVersion int32       `json:"expected_instruction_version"`
	ExpectedInstructionHash    string      `json:"expected_instruction_hash"`
	ExpectedManifestID         string      `json:"expected_manifest_id"`
	ExpectedManifestVersion    int32       `json:"expected_manifest_version"`
	ExpectedManifestHash       string      `json:"expected_manifest_hash"`
	ExpectedManifestSource     string      `json:"expected_manifest_source"`
}

func (q *Queries) CompleteRoleRun(ctx context.Context, arg CompleteRoleRunParams) (RoleRun, error) {
	row := q.db.QueryRow(ctx, completeRoleRun,
		arg.Status,
		arg.ModelID,
		arg.LatencyMs,
		arg.Usage,
		arg.ErrorCode,
		arg.OwnerID,
		arg.CognitiveRunID,
		arg.RoleRunID,
		arg.ExpectedPhase,
		arg.ExpectedPerspective,
		arg.ExpectedInstructionID,
		arg.ExpectedInstructionVersion,
		arg.ExpectedInstructionHash,
		arg.ExpectedManifestID,
		arg.ExpectedManifestVersion,
		arg.ExpectedManifestHash,
		arg.ExpectedManifestSource,
	)
	var i RoleRun
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CognitiveRunID,
		&i.Phase,
		&i.Perspective,
		&i.Status,
		&i.ModelID,
		&i.InstructionID,
		&i.InstructionVersion,
		&i.InstructionHash,
		&i.ManifestID,
		&i.ManifestVersion,
		&i.ManifestHash,
		&i.LatencyMs,
		&i.Usage,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.ManifestSource,
	)
	return i, err
}

const completeToolCall = `-- name: CompleteToolCall :one
UPDATE sonata.tool_calls
SET status = $1,
    result_metadata = $2::jsonb,
    completed_at = $3
WHERE owner_id = $4
  AND cognitive_run_id = $5
  AND id = $6
RETURNING id, owner_id, cognitive_run_id, role_run_id, tool_name, status, request_metadata, result_metadata, created_at, completed_at
`

type CompleteToolCallParams struct {
	Status         string      `json:"status"`
	ResultMetadata []byte      `json:"result_metadata"`
	CompletedAt    *time.Time  `json:"completed_at"`
	OwnerID        string      `json:"owner_id"`
	CognitiveRunID pgtype.UUID `json:"cognitive_run_id"`
	ToolCallID     pgtype.UUID `json:"tool_call_id"`
}

func (q *Queries) CompleteToolCall(ctx context.Context, arg CompleteToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, completeToolCall,
		arg.Status,
		arg.ResultMetadata,
		arg.CompletedAt,
		arg.OwnerID,
		arg.CognitiveRunID,
		arg.ToolCallID,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CognitiveRunID,
		&i.RoleRunID,
		&i.ToolName,
		&i.Status,
		&i.RequestMetadata,
		&i.ResultMetadata,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createCognitiveRun = `-- name: CreateCognitiveRun :one
INSERT INTO sonata.cognitive_runs (
    owner_id,
    conversation_id,
    request_message_id,
    route,
    status,
    started_at,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::jsonb
)
RETURNING id, owner_id, conversation_id, request_message_id, route, status, started_at, completed_at, metadata
`

type CreateCognitiveRunParams struct {
	OwnerID          string    `json:"owner_id"`
	ConversationID   string    `json:"conversation_id"`
	RequestMessageID string    `json:"request_message_id"`
	Route            string    `json:"route"`
	Status           string    `json:"status"`
	StartedAt        time.Time `json:"started_at"`
	Metadata         []byte    `json:"metadata"`
}

func (q *Queries) CreateCognitiveRun(ctx context.Context, arg CreateCognitiveRunParams) (CognitiveRun, error) {
	row := q.db.QueryRow(ctx, createCognitiveRun,
		arg.OwnerID,
		arg.ConversationID,
		arg.RequestMessageID,
		arg.Route,
		arg.Status,
		arg.StartedAt,
		arg.Metadata,
	)
	var i CognitiveRun
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.RequestMessageID,
		&i.Route,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const createRoleRun = `-- name: CreateRoleRun :one
INSERT INTO sonata.role_runs (
    owner_id,
    cognitive_run_id,
    phase,
    perspective,
    status,
    model_id,
    instruction_id,
    instruction_version,
    instruction_hash,
    manifest_id,
    manifest_version,
    manifest_hash,
    manifest_source,
    latency_ms,
    usage,
    error_code,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15::jsonb,
    $16,
    $17
)
RETURNING id, owner_id, cognitive_run_id, phase, perspective, status, model_id, instruction_id, instruction_version, instruction_hash, manifest_id, manifest_version, manifest_hash, latency_ms, usage, error_code, created_at, manifest_source
`

type CreateRoleRunParams struct {
	OwnerID            string      `json:"owner_id"`
	CognitiveRunID     pgtype.UUID `json:"cognitive_run_id"`
	Phase              string      `json:"phase"`
	Perspective        string      `json:"perspective"`
	Status             string      `json:"status"`
	ModelID            string      `json:"model_id"`
	InstructionID      string      `json:"instruction_id"`
	InstructionVersion int32       `json:"instruction_version"`
	InstructionHash    string      `json:"instruction_hash"`
	ManifestID         string      `json:"manifest_id"`
	ManifestVersion    int32       `json:"manifest_version"`
	ManifestHash       string      `json:"manifest_hash"`
	ManifestSource     string      `json:"manifest_source"`
	LatencyMs          int64       `json:"latency_ms"`
	Usage              []byte      `json:"usage"`
	ErrorCode          string      `json:"error_code"`
	CreatedAt          time.Time   `json:"created_at"`
}

func (q *Queries) CreateRoleRun(ctx context.Context, arg CreateRoleRunParams) (RoleRun, error) {
	row := q.db.QueryRow(ctx, createRoleRun,
		arg.OwnerID,
		arg.CognitiveRunID,
		arg.Phase,
		arg.Perspective,
		arg.Status,
		arg.ModelID,
		arg.InstructionID,
		arg.InstructionVersion,
		arg.InstructionHash,
		arg.ManifestID,
		arg.ManifestVersion,
		arg.ManifestHash,
		arg.ManifestSource,
		arg.LatencyMs,
		arg.Usage,
		arg.ErrorCode,
		arg.CreatedAt,
	)
	var i RoleRun
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CognitiveRunID,
		&i.Phase,
		&i.Perspective,
		&i.Status,
		&i.ModelID,
		&i.InstructionID,
		&i.InstructionVersion,
		&i.InstructionHash,
		&i.ManifestID,
		&i.ManifestVersion,
		&i.ManifestHash,
		&i.LatencyMs,
		&i.Usage,
		&i.ErrorCode,
		&i.CreatedAt,
		&i.ManifestSource,
	)
	return i, err
}

const getCognitiveRun = `-- name: GetCognitiveRun :one
SELECT id, owner_id, conversation_id, request_message_id, route, status, started_at, completed_at, metadata
FROM sonata.cognitive_runs
WHERE owner_id = $1
  AND id = $2
`

type GetCognitiveRunParams struct {
	OwnerID        string      `json:"owner_id"`
	CognitiveRunID pgtype.UUID `json:"cognitive_run_id"`
}

func (q *Queries) GetCognitiveRun(ctx context.Context, arg GetCognitiveRunParams) (CognitiveRun, error) {
	row := q.db.QueryRow(ctx, getCognitiveRun, arg.OwnerID, arg.CognitiveRunID)
	var i CognitiveRun
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.ConversationID,
		&i.RequestMessageID,
		&i.Route,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.Metadata,
	)
	return i, err
}

const insertProviderUsage = `-- name: InsertProviderUsage :one
INSERT INTO sonata.provider_usage (
    owner_id,
    cognitive_run_id,
    role_run_id,
    provider,
    model_id,
    input_tokens,
    output_tokens,
    cached_tokens,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9
)
RETURNING id, owner_id, cognitive_run_id, role_run_id, provider, model_id, input_tokens, output_tokens, cached_tokens, created_at
`

type InsertProviderUsageParams struct {
	OwnerID        string      `json:"owner_id"`
	CognitiveRunID pgtype.UUID `json:"cognitive_run_id"`
	RoleRunID      pgtype.UUID `json:"role_run_id"`
	Provider       string      `json:"provider"`
	ModelID        string      `json:"model_id"`
	InputTokens    int64       `json:"input_tokens"`
	OutputTokens   int64       `json:"output_tokens"`
	CachedTokens   int64       `json:"cached_tokens"`
	CreatedAt      time.Time   `json:"created_at"`
}

func (q *Queries) InsertProviderUsage(ctx context.Context, arg InsertProviderUsageParams) (ProviderUsage, error) {
	row := q.db.QueryRow(ctx, insertProviderUsage,
		arg.OwnerID,
		arg.CognitiveRunID,
		arg.RoleRunID,
		arg.Provider,
		arg.ModelID,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CachedTokens,
		arg.CreatedAt,
	)
	var i ProviderUsage
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CognitiveRunID,
		&i.RoleRunID,
		&i.Provider,
		&i.ModelID,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CachedTokens,
		&i.CreatedAt,
	)
	return i, err
}

const insertToolCall = `-- name: InsertToolCall :one
INSERT INTO sonata.tool_calls (
    owner_id,
    cognitive_run_id,
    role_run_id,
    tool_name,
    status,
    request_metadata,
    result_metadata,
    created_at
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6::jsonb,
    $7::jsonb,
    $8
)
RETURNING id, owner_id, cognitive_run_id, role_run_id, tool_name, status, request_metadata, result_metadata, created_at, completed_at
`

type InsertToolCallParams struct {
	OwnerID         string      `json:"owner_id"`
	CognitiveRunID  pgtype.UUID `json:"cognitive_run_id"`
	RoleRunID       pgtype.UUID `json:"role_run_id"`
	ToolName        string      `json:"tool_name"`
	Status          string      `json:"status"`
	RequestMetadata []byte      `json:"request_metadata"`
	ResultMetadata  []byte      `json:"result_metadata"`
	CreatedAt       time.Time   `json:"created_at"`
}

func (q *Queries) InsertToolCall(ctx context.Context, arg InsertToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, insertToolCall,
		arg.OwnerID,
		arg.CognitiveRunID,
		arg.RoleRunID,
		arg.ToolName,
		arg.Status,
		arg.RequestMetadata,
		arg.ResultMetadata,
		arg.CreatedAt,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.CognitiveRunID,
		&i.RoleRunID,
		&i.ToolName,
		&i.Status,
		&i.RequestMetadata,
		&i.ResultMetadata,
		&i.CreatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listRoleRuns = `-- name: ListRoleRuns :many
SELECT id, owner_id, cognitive_run_id, phase, perspective, status, model_id, instruction_id, instruction_version, instruction_hash, manifest_id, manifest_version, manifest_hash, latency_ms, usage, error_code, created_at, manifest_source
FROM sonata.role_runs
WHERE owner_id = $1
  AND cognitive_run_id = $2
ORDER BY created_at, id
`

type ListRoleRunsParams struct {
	OwnerID        string      `json:"owner_id"`
	CognitiveRunID pgtype.UUID `json:"cognitive_run_id"`
}

func (q *Queries) ListRoleRuns(ctx context.Context, arg ListRoleRunsParams) ([]RoleRun, error) {
	rows, err := q.db.Query(ctx, listRoleRuns, arg.OwnerID, arg.CognitiveRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RoleRun{}
	for rows.Next() {
		var i RoleRun
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CognitiveRunID,
			&i.Phase,
			&i.Perspective,
			&i.Status,
			&i.ModelID,
			&i.InstructionID,
			&i.InstructionVersion,
			&i.InstructionHash,
			&i.ManifestID,
			&i.ManifestVersion,
			&i.ManifestHash,
			&i.LatencyMs,
			&i.Usage,
			&i.ErrorCode,
			&i.CreatedAt,
			&i.ManifestSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listToolCalls = `-- name: ListToolCalls :many
SELECT id, owner_id, cognitive_run_id, role_run_id, tool_name, status, request_metadata, result_metadata, created_at, completed_at
FROM sonata.tool_calls
WHERE owner_id = $1
  AND cognitive_run_id = $2
ORDER BY created_at, id
`

type ListToolCallsParams struct {
	OwnerID        string      `json:"owner_id"`
	CognitiveRunID pgtype.UUID `json:"cognitive_run_id"`
}

func (q *Queries) ListToolCalls(ctx context.Context, arg ListToolCallsParams) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, listToolCalls, arg.OwnerID, arg.CognitiveRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.CognitiveRunID,
			&i.RoleRunID,
			&i.ToolName,
			&i.Status,
			&i.RequestMetadata,
			&i.ResultMetadata,
			&i.CreatedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
